name: 'Setup environment'
description: 'Sets up environment'
inputs:
  node:
    description: 'Node.js version'
    required: true
  os:
    description: 'runs-on'
    required: true

runs:
  using: "composite"
  steps:

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Cache node-gyp Linux
      if: runner.os == 'Linux'
      uses: actions/cache@v4
      env:
        cache-name: cache-node-gyp
      with:
        path: ~/.cache/node-gyp
        key: '${{ inputs.os }}-${{ inputs.node}}'

    - name: Cache node-gyp macOs
      if: runner.os == 'macOS'
      uses: actions/cache@v4
      env:
        cache-name: cache-node-gyp
      with:
        path: ~/Library/Caches/node-gyp
        key: '${{ inputs.os }}-${{ inputs.node}}'

    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ inputs.os }}-${{ inputs.node }}-${{ hashFiles('package-lock.json') }}

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # SDK Version to use; x will use the latest version of the 8.0 channel

    - name: Setup Mono
      if: inputs.os == 'macos-14' || inputs.os == 'macos-15'
      shell: bash
      run: |
        brew install mono
        brew reinstall pkg-config

    - name: Setup Mono
      if: inputs.os == 'macos-13'
      shell: bash
      run: |
        brew reinstall mono --overwrite
        brew reinstall pkg-config --overwrite


    - name: Versions
      shell: bash
      run: |
        node -v && npm -v && dotnet --version && node -p process.platform && node -p process.arch

    - if: runner.os == 'macOS' && inputs.node <= 16
      shell: bash
      name: Add missing packages for macOS NodeJs 16 
      run: |
        pip install setuptools

    - name: npm install
      shell: bash
      run: npm i
